name: Spring Tests

on:
  push:
    branches: [ master, refactor/master ]
  pull_request:
    branches: [ master, refactor/master ]

jobs:
  build:
    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_USER: user
          MYSQL_PASSWORD: 1234
          MYSQL_ROOT_PASSWORD: toor
          MYSQL_DATABASE: video_hosting_db
          SPRING_PROFILES_ACTIVE: docker
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Test Spring
      run: ./mvnw test
      env:
        SPRING_PROFILES_ACTIVE: docker
        AMAZON_ACCESS_KEY: ${{ secrets.AMAZON_ACCESS_KEY }}
        AMAZON_SECRET_KEY: ${{ secrets.AMAZON_SECRET_KEY }}
